name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag ghcr.io/acovrig/church-audio-sync:latest
    - name: Login to the registry
      run: echo $GITHUB_TOKEN | docker login ghcr.io -u USERNAME --password-stdin
    - name: Push to the registry
      run: docker push ghcr.io/acovrig/church-audio-sync:latest
